# Generated by Django 5.1.1 on 2024-10-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_audience_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='_type',
            field=models.CharField(choices=[('lecture', 'Лекция'), ('seminar', 'Семинар'), ('examination', 'Экзамен')], default='лекция', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='speaker',
            field=models.CharField(default='лектор', max_length=70),
            preserve_default=False,
        ),
    ]
