# Generated by Django 5.1.1 on 2024-10-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_campus_is_active_alter_reservation__type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='_type',
            new_name='type',
        ),
    ]
