# Generated by Django 5.1.1 on 2024-10-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
