# Generated by Django 5.1.1 on 2024-10-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation__type_reservation_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='_type',
            field=models.CharField(choices=[('lecture', 'Лекция'), ('seminar', 'Семинар'), ('examination', 'Экзамен')], default='Лекция', max_length=20),
        ),
    ]
